server:
  port: 8080

spring:
  application:
    name: newNewsConsumer
  profiles:
    active: wiki

logging:
  config: classpath:logback-spring.xml
  path: ./logs/newNewsConsumer/${spring.profiles.active}/
  pattern:
    dateformat: yyyyMMdd HH:mm:ss:SSS
    level: info

http:
  defaultMaxPerRoute: 10
  maxTotal: 1000
  staleConnectionCheckEnabled: true
  socketTimeout: 10000
  connectTimeout: 1000
  connectionRequestTimeout: 5000

elasticsearch:
  connect-timeout: 500000
  socket-timeout: 400000
  connection-request-timeout: 1000
  bulk:
    size: 10
    flush: 5000
    concurrent: 3