server:
  port: 8081

kafka:
  input:
    topic: spider-formated
    appId: monthly
    hosts: 10.0.9.62:9092,10.0.9.63:9092,10.0.9.67:9092
  output:
    topic: newton-article

elasticsearch:
  address: 10.0.9.80:9200,10.0.9.81:9200
  index: newton_original_doc_%s
  bulk:
    flush: 500
    size: 10

langid:
  url: http://10.0.13.204:8080/langId

summary:
  url: http://10.0.3.64:80/text-rank

spring:
  redis:
    host: r-uf6msugry3djgblvj7.redis.rds.aliyuncs.com
    password: HDRM3XTYQujrTKTh
    port: 6379