server:
  port: 8084

isTest: false

kafka:
  input:
    topic: spider-formated-answer
    appId: blog
    hosts: 10.0.9.62:9092,10.0.9.63:9092,10.0.9.67:9092
  output:
    topic: newton-article

elasticsearch:
  address: 10.0.15.27:9200,10.0.15.28:9200
  bulk:
    flush: 5000
    size: 10
  index: newton_blog_20191228

remote-analysis:
  url: http://10.0.1.153:80/analyze

summary:
  url: http://10.0.3.64:80/text-rank

spring:
  redis:
    host: r-uf6msugry3djgblvj7.redis.rds.aliyuncs.com
    password: HDRM3XTYQujrTKTh
    port: 6379