server:
  port: 8080

spring:
  application:
    name: newNewsConsumer
  profiles:
    active: job

logging:
  config: classpath:logback-spring.xml
  path: ./logs/newNewsConsumer/${spring.profiles.active}/
  pattern:
    dateformat: yyyyMMdd HH:mm:ss:SSS
    level: info

http:
  defaultMaxPerRoute: 10
  maxTotal: 1000
  staleConnectionCheckEnabled: true
  socketTimeout: 10000
  connectTimeout: 1000
  connectionRequestTimeout: 5000
