server:
  port: 8080

spring:
  application:
    name: newNewsConsumer
  profiles:
    active: ${ACTIVE_KEY}

logging:
  config: classpath:logback-spring.xml
  path: /usr/local/logs/newNewsConsumer/${spring.profiles.active}/
  pattern:
    dateformat: yyyyMMdd HH:mm:ss:SSS
    level: info

http:
  defaultMaxPerRoute: 20
  maxTotal: 100
  staleConnectionCheckEnabled: true
  socketTimeout: 10000
  connectTimeout: 1000
  connectionRequestTimeout: 500

tasks:
  enableDailyJob: true
  enableMonthlyJob: true