server:
  port: 8084

isTest: false
isRerun: false

kafka:
  input:
    topic: spider-formated-blog
    appId: blog
    hosts: 10.0.9.62:9092,10.0.9.63:9092,10.0.9.67:9092
  output:
    topic: newton-article

elasticsearch:
  address: 10.0.15.27:9200,10.0.15.28:9200
  bulk:
    flush: 5000
    size: 10
  index: newton_blog
